//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goncharov_Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int id { get; set; }
        public int responsible { get; set; }
        public int client { get; set; }
        public int room { get; set; }
        public int status { get; set; }
        public System.DateTime date_of_booking { get; set; }
        public System.DateTime checkin_date { get; set; }
        public System.DateTime leaving_date { get; set; }
        public string add_requirements { get; set; }
    
        public virtual Booking_status Booking_status { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual Room Room1 { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
